// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListNerdFontIcons():Promise<Array<main.NerdFontIcon>>;

export function ListSvgIcons():Promise<Array<main.SvgIcon>>;
