// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListNerdFontIcons() {
  return window['go']['main']['App']['ListNerdFontIcons']();
}

export function ListSvgIcons() {
  return window['go']['main']['App']['ListSvgIcons']();
}
